package com.fsck.k9.backend.katzenpost

import java.util.*

object KatzenpostNameGenerator {
    val animals = listOf(
            "aardvark", "aardwolf", "abalone", "acaciarat", "acouchi", "addax",
            "adder", "adouri", "aegeancat", "agama", "agouti", "aidi", "airedale",
            "akitainu", "albatross", "albino", "alleycat", "alligator", "alpaca",
            "ambushbug", "ammonite", "amoeba", "amphibian", "amphiuma", "anaconda",
            "anchovy", "andeancat", "anemone", "angelfish", "angora", "anhinga",
            "ankole", "annelid", "annelida", "anole", "ant", "antbear", "anteater",
            "antelope", "antlion", "anura", "aoudad", "apatosaur", "ape", "aphid",
            "appaloosa", "aracari", "arachnid", "arawana", "arcticfox", "argali",
            "argusfish", "arkshell", "armadillo", "armedcrab", "armyant",
            "armyworm", "arrowana", "arrowcrab", "arrowworm", "aruanas",
            "asianlion", "asp", "ass", "astarte", "atlasmoth", "auk", "auklet",
            "aurochs", "avians", "avocet", "axisdeer", "axolotl", "ayeaye",
            "aztecant", "azurevase", "babirusa", "baboon", "bactrian", "badger",
            "bagworm", "baiji", "baldeagle", "bandicoot", "banteng", "barasinga",
            "barb", "barbet", "barnacle", "barnowl", "barracuda", "basenji",
            "basil", "basilisk", "bass", "bat", "bats", "beagle", "bear",
            "beauceron", "beaver", "bedbug", "bee", "beetle", "bellfrog",
            "bellsnake", "betafish", "bettong", "bighorn", "bilby", "billygoat",
            "binturong", "bird", "bison", "bittern", "blackbear", "blackbird",
            "blackbuck", "blackfish", "blackfly", "blacklab", "blesbok", "blobfish",
            "blowfish", "bluebird", "bluefish", "bluegill", "bluejay", "blueshark",
            "bluet", "bluewhale", "boa", "boar", "bobcat", "bobolink", "bobwhite",
            "bongo", "bonobo", "booby", "borer", "borzoi", "boto", "boubou",
            "boutu", "bovine", "brant", "bream", "bronco", "brownbear", "buck",
            "budgie", "bufeo", "buffalo", "bug", "bull", "bullfrog", "bumblebee",
            "bunny", "bunting", "burro", "bushbaby", "bustard", "butterfly",
            "buzzard", "caecilian", "caiman", "calf", "camel", "canary", "canine",
            "capybara", "caracal", "cardinal", "caribou", "carp", "cassowary",
            "cat", "catbird", "catfish", "cats", "cattle", "caudata", "cavy",
            "centipede", "cero", "chafer", "chameleon", "chamois", "cheetah",
            "chick", "chickadee", "chicken", "chihuahua", "chipmunk", "chital",
            "chrysalis", "cicada", "cirriped", "civet", "clam", "clingfish",
            "clumber", "coati", "cob", "cobra", "cock", "cockatiel", "cockatoo",
            "cockroach", "cod", "collie", "colt", "comet", "conch", "condor",
            "coney", "conure", "cony", "coot", "cooter", "copepod", "coqui",
            "coral", "cormorant", "cornsnake", "cougar", "cow", "cowbird", "cowrie",
            "coyote", "coypu", "crab", "crane", "cranefly", "crayfish", "creature",
            "cricket", "crocodile", "crossbill", "crow", "cub", "cuckoo", "cur",
            "curassow", "curlew", "cuscus", "cusimanse", "cutworm", "cygnet",
            "dachshund", "dairycow", "dalmatian", "damselfly", "dartfrog", "dassie",
            "dassierat", "deer", "deermouse", "degu", "degus", "devilfish",
            "dikdik", "dikkops", "dingo", "dinosaur", "dipper", "discus", "dodo",
            "dodobird", "doe", "dog", "dogfish", "dolphin", "donkey", "dorado",
            "dore", "dorking", "dormouse", "dotterel", "dove", "dowitcher",
            "dragon", "dragonfly", "drake", "drever", "dromedary", "drongo", "duck",
            "duckling", "dugong", "duiker", "dunlin", "dunnart", "eagle",
            "earthworm", "earwig", "echidna", "eel", "eeve", "eft", "egg", "egret",
            "eider", "eland", "elephant", "elk", "elkhound", "elver", "emu",
            "equine", "erin", "ermine", "erne", "eskimodog", "esok", "ewe", "eyas",
            "eyra", "fairyfly", "falcon", "fantail", "fanworms", "fawn", "feline",
            "fennecfox", "ferret", "finch", "finwhale", "fireant", "firecrest",
            "firefly", "fish", "flamingo", "flatfish", "flea", "flee", "flicker",
            "flies", "flounder", "fluke", "fly", "flyingfox", "foal", "fossa",
            "fowl", "fox", "foxhound", "frog", "frogmouth", "fruitbat", "fruitfly",
            "fugu", "fulmar", "furseal", "gadwall", "galago", "galah", "gallinule",
            "gander", "gannet", "gar", "garpike", "gaur", "gavial", "gazelle",
            "gecko", "geese", "gelada", "gelding", "gemsbok", "gemsbuck", "genet",
            "gerbil", "gerenuk", "gharial", "gibbon", "giraffe", "glassfrog",
            "globefish", "glowworm", "gnat", "gnu", "goa", "goat", "godwit",
            "goitered", "goldeneye", "goldfinch", "goldfish", "gonolek", "goose",
            "goosefish", "gopher", "goral", "gorilla", "goshawk", "gosling",
            "gourami", "grackle", "grayfox", "grayling", "graywolf", "greatdane",
            "grebe", "grison", "grosbeak", "groundhog", "grouper", "grouse", "grub",
            "grunion", "guanaco", "guillemot", "guineapig", "gull", "guppy",
            "gypsymoth", "gyrfalcon", "hackee", "haddock", "hagfish", "hake",
            "halcyon", "halibut", "halicore", "hamadryad", "hamadryas", "hammerkop",
            "hamster", "hapuka", "hapuku", "hare", "harpseal", "harrier", "hart",
            "hawk", "hedgehog", "heifer", "hen", "herald", "heron", "herring",
            "hind", "hoatzin", "hog", "hogget", "hoiho", "hoki", "honeybee",
            "hoopoe", "hornbill", "hornet", "hornshark", "horse", "horsefly",
            "hound", "housefly", "hoverfly", "huemul", "huia", "human", "husky",
            "hydra", "hyena", "hyrax", "ibex", "ibis", "ibisbill", "icefish",
            "ichidna", "iggypops", "iguana", "iguanodon", "imago", "impala",
            "incatern", "inchworm", "indiancow", "indri", "inganue", "insect",
            "isopod", "ivorygull", "izuthrush", "jabiru", "jackal", "jaeger",
            "jaguar", "javalina", "jay", "jellyfish", "jenny", "jerboa", "joey",
            "johndory", "junco", "junebug", "kagu", "kakapo", "kakarikis",
            "kangaroo", "karakul", "katydid", "kawala", "kestrel", "kid",
            "killdeer", "killifish", "kingbird", "kinglet", "kingsnake", "kinkajou",
            "kiskadee", "kite", "kitfox", "kitten", "kittiwake", "kitty", "kiwi",
            "koala", "koalabear", "kob", "koi", "koodoo", "kouprey", "krill",
            "kudu", "kusimanse", "lacewing", "ladybird", "ladybug", "lamb",
            "lamprey", "langur", "lark", "larva", "lcont", "leafbird", "leafwing",
            "leech", "lemming", "lemur", "leopard", "leveret", "lhasaapso", "lice",
            "liger", "limpet", "limpkin", "ling", "lion", "lionfish", "lizard",
            "llama", "lobo", "lobster", "locust", "longhorn", "longspur", "loon",
            "lorikeet", "loris", "louse", "lovebird", "lowchen", "lunamoth",
            "lungfish", "lynx ", "lynx", "macaque", "macaw", "macropod", "maggot",
            "magpie", "maiasaura", "malamute", "mallard", "mamba", "mammal",
            "mammoth", "manatee", "mandrill", "mangabey", "manta", "mantaray",
            "mantid", "mantis", "mantisray", "manxcat", "mara", "marabou", "mare",
            "marlin", "marmoset", "marmot", "marten", "martin", "mastiff",
            "mastodon", "mayfly", "mealworm", "meerkat", "merganser", "merlin",
            "mice", "midge", "milksnake", "millipede", "minibeast", "mink",
            "minnow", "mite", "moa", "mole", "mollies", "mollusk", "molly",
            "monarch", "mongoose", "mongrel", "monkey", "monkfish ", "moorhen",
            "moose", "moray", "morayeel", "morpho", "mosasaur", "mosquito", "moth",
            "motmot", "mouflon", "mouse", "mousebird", "mudpuppy", "mule", "mullet",
            "muntjac", "murrelet", "muskox", "muskrat", "mussaurus", "mussel",
            "mustang", "mutt", "myna", "mynah", "myotis ", "nabarlek", "nag",
            "naga", "nagapies", "nandine", "nandoo", "nandu", "narwhal", "narwhale",
            "nauplius", "nautilus", "nematode", "nene", "neontetra", "nerka",
            "newt", "nighthawk", "nightjar", "nilgai", "noctilio", "noctule",
            "noddy", "norwayrat", "numbat", "nuthatch", "nutria", "nyala", "nymph",
            "ocelot", "octopus", "okapi", "olingo", "olm", "opossum", "orangutan",
            "orca", "oriole", "oryx", "osprey", "ostracod", "ostrich", "otter",
            "ovenbird", "owl", "ox", "oxen", "oxpecker", "oyster", "paca ",
            "pachyderm", "panda", "pangolin", "panther", "paperwasp", "papillon",
            "parakeet", "parrot", "partridge", "peacock", "peafowl", "peccary",
            "pekingese", "pelican", "penguin", "perch", "pewee", "phalarope",
            "pheasant", "phoebe", "phoenix", "pig", "pigeon", "piglet", "pika",
            "pike", "pilchard", "pinniped", "pintail", "pipit", "piranha",
            "pitbull", "pittabird", "plankton", "platypus", "plover", "polarbear",
            "polecat", "polliwog", "polyp", "pony", "pooch", "poodle", "porcupine",
            "porpoise", "possum", "prawn", "primate", "pronghorn", "ptarmigan",
            "puffer", "puffin", "pug", "pullet", "puma", "pupa", "pupfish", "puppy",
            "pussycat", "pygmy", "python", "quagga", "quahog", "quail", "queenant",
            "queenbee", "quelea", "quetzal", "quillback", "quokka", "quoll",
            "rabbit", "raccoon", "racer", "ragfish", "rail", "ram", "raptors",
            "rasbora", "rat", "ratfish", "rattail", "raven", "ray", "redhead",
            "redpoll", "redstart", "reindeer", "reptile", "reynard", "rhea",
            "rhino", "ringworm", "roach", "roan", "robberfly", "robin", "rockrat",
            "rodent", "roebuck", "roller", "rook", "rooster", "sable", "saiga",
            "salmon", "sambar", "sandpiper", "sapsucker", "sardine", "sawfish",
            "scallop", "scarab", "scaup", "schnauzer", "scorpion", "scoter",
            "screamer", "seabird", "seagull", "seahog", "seahorse", "seal",
            "sealion", "seamonkey", "seaslug", "seaurchin", "seriema", "serpent",
            "serval", "shark", "sheep", "sheldrake", "shelduck", "shibainu",
            "shihtzu", "shorebird", "shoveler", "shrew", "shrike", "shrimp",
            "siamang", "sifaka", "silkworm", "silverfox", "siskin", "skimmer",
            "skink", "skipper", "skua", "skunk", "skylark", "sloth", "slothbear",
            "slug", "smelts", "smew", "snail", "snake", "snipe", "snowdog",
            "snowgeese", "snowyowl", "solenodon", "solitaire", "songbird", "sora",
            "sow", "spadefoot", "sparrow", "sphinx", "spider", "spiketail",
            "sponge", "spoonbill", "springbok", "squab", "squamata", "squeaker",
            "squid", "squirrel", "stag", "stallion", "starfish", "starling",
            "steed", "steer", "stilt", "stingray", "stinkbug", "stinkpot", "stoat",
            "stonefly", "stork", "stud", "sturgeon", "sunbear", "sunfish",
            "swallow", "swan", "swellfish", "swift", "swordfish", "tadpole", "tahr",
            "takin", "tamarin", "tanager", "tapaculo", "tapeworm", "tapir",
            "tarantula", "tarpan", "tarsier", "taruca", "tattler", "tayra", "teal",
            "tegus", "teledu", "tench", "tenrec", "termite", "tern", "terrapin",
            "terrier", "thrasher", "thrip", "thrush", "thylacine", "tick", "tiger",
            "tigermoth", "tilefish", "tinamou", "titi", "titmouse", "toad",
            "toadfish", "tomtit ", "topi", "tortoise", "toucan", "towhee",
            "tragopan", "trex", "trogon", "trout", "tsetsefly", "tuatara", "tuna",
            "turaco", "turkey", "turnstone", "turtle", "uakari", "ugandakob",
            "umbrette", "unau", "ungulate", "unicorn", "upupa", "urchin", "urial",
            "urson", "urubu", "urus", "urutu", "urva", "vaquita", "veery", "verdin",
            "vervet", "vicuna", "viper", "viperfish", "vireo", "vixen", "vole",
            "volvox", "vulture", "wallaby", "wallaroo", "walleye", "walrus",
            "warbler", "warthog", "wasp", "waterbuck", "waterbug", "waterdogs",
            "watussi", "waxwing", "weasel", "weevil", "whale", "whapuku", "whelp",
            "whimbrel", "whippet", "whiteeye", "whooper", "widgeon", "wildcat",
            "willet", "wireworm", "wisent", "wolf", "wolverine", "wombat",
            "woodborer", "woodchuck", "woodcock", "worm", "wrasse", "wreckfish",
            "wren", "wryneck", "wyvern", "xanclomys", "xantus", "xeme", "xenarthra",
            "xenops", "xenopus", "xenurine", "xerus", "xiphias", "xoni", "xrayfish",
            "xraytetra", "yaffle", "yak", "yapok", "yardant", "yearling", "yeti",
            "ynambu", "yucker", "zander", "zebra", "zebradove", "zebrafish", "zebu",
            "zenaida", "zeren", "zopilote", "zorilla"
    )

    val adjectives = listOf(
            "defiant", "homeless", "adorable", "delightful", "homely", "quant",
            "adventurous", "depressed", "horrible", "aggressive", "determined",
            "hungry", "real", "agreeable", "different", "hurt", "relieved", "alert",
            "difficult", "repulsive", "alive", "disgusted", "ill", "rich", "amused",
            "distinct", "important", "angry", "disturbed", "impossible", "scary",
            "annoyed", "dizzy", "inexpensive", "selfish", "annoying", "doubtful",
            "innocent", "shiny", "anxious", "drab", "inquisitive", "shy",
            "arrogant", "dull", "itchy", "silly", "ashamed", "sleepy", "attractive",
            "eager", "jealous", "smiling", "average", "easy", "jittery", "smoggy",
            "awful", "elated", "jolly", "sore", "elegant", "joyous", "sparkling",
            "bad", "embarrassed", "splendid", "beautiful", "enchanting", "kind",
            "spotless", "better", "encouraging", "stormy", "bewildered",
            "energetic", "lazy", "strange", "black", "enthusiastic", "light",
            "stupid", "bloody", "envious", "lively", "successful", "blue", "evil",
            "lonely", "super", "excited", "long", "blushing",
            "expensive", "lovely", "talented", "bored", "exuberant", "lucky",
            "tame", "brainy", "tender", "brave", "fair", "magificent", "tense",
            "breakable", "faithful", "misty", "terrible", "bright", "famous",
            "modern", "tasty", "busy", "fancy", "motionless", "thankful",
            "fantastic", "muddy", "thoughtful", "calm", "fierce", "mushy",
            "thoughtless", "careful", "filthy", "mysterious", "tired", "cautious",
            "fine", "tough", "charming", "foolish", "nasty", "troubled", "cheerful",
            "fragile", "naughty", "clean", "frail", "nervous", "ugliest", "clear",
            "frantic", "nice", "ugly", "clever", "friendly", "nutty",
            "uninterested", "cloudy", "frightened", "unsightly", "clumsy", "funny",
            "obedient", "unusual", "colorful", "obnoxious", "upset", "combative",
            "gentle", "odd", "uptight", "comfortable", "gifted",
            "concerned", "glamorous", "open", "vast", "condemned", "gleaming",
            "outrageous", "victorious", "confused", "glorious", "outstanding",
            "vivacious", "cooperative", "good", "courageous", "gorgeous", "panicky",
            "wandering", "crazy", "graceful", "perfect", "weary", "creepy",
            "grieving", "plain", "wicked", "crowded", "grotesque", "pleasant",
            "cruel", "grumpy", "poised", "wild", "curious", "poor",
            "witty", "cute", "handsome", "powerful", "worrisome", "happy",
            "precious", "worried", "dangerous", "healthy", "prickly", "wrong",
            "dark", "helpful", "proud", "dead", "helpless", "puzzled", "zany",
            "defeated", "hilarious", "zealous"
    )

    val random = Random()
    fun getRandomName(): String {
        val randomAdjective = adjectives[random.nextInt(adjectives.size)]
        val randomAnimal = animals[random.nextInt(animals.size)]
        val randomNumber = random.nextInt(100) + 1

        return randomAdjective.capitalize() + randomAnimal.capitalize() + randomNumber
    }

}
